import { EntityKind } from '@/types';
import type { UnitDef } from './unit-def';

/** Stats and costs for all buildings (player and enemy). */
export const BUILDING_DEFS: Partial<Record<EntityKind, UnitDef>> = {
  [EntityKind.Lodge]: {
    hp: 1500,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 200,
    logCost: 150,
    foodProvided: 8,
  },
  [EntityKind.Burrow]: {
    hp: 300,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 0,
    logCost: 75,
    foodProvided: 6,
    isWing: true,
  },
  [EntityKind.Armory]: {
    hp: 500,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 180,
    logCost: 120,
    isWing: true,
  },
  [EntityKind.Tower]: {
    hp: 500,
    speed: 0,
    damage: 10,
    attackRange: 200,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 200,
    logCost: 250,
  },
  [EntityKind.Watchtower]: {
    hp: 800,
    speed: 0,
    damage: 15,
    attackRange: 280,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 400,
    logCost: 350,
  },
  [EntityKind.PredatorNest]: {
    hp: 1000,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
  },
  [EntityKind.Wall]: {
    hp: 400,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 0,
    logCost: 50,
  },
  [EntityKind.LookoutPost]: {
    hp: 200,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 100,
    logCost: 75,
  },
  [EntityKind.FishingHut]: {
    hp: 250,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 100,
    logCost: 75,
    foodProvided: 2,
    isWing: true,
  },
  [EntityKind.HerbalistHut]: {
    hp: 300,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 150,
    logCost: 100,
    isWing: true,
  },
  // --- v1.5.0 ---
  [EntityKind.Market]: {
    hp: 100,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 150,
    logCost: 100,
    isWing: true,
  },
  // --- v2.0.0 ---
  [EntityKind.Dock]: {
    hp: 120,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 200,
    logCost: 150,
    foodProvided: 2,
    isWing: true,
  },
  [EntityKind.WallGate]: {
    hp: 80,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 60,
    logCost: 40,
  },
  [EntityKind.Shrine]: {
    hp: 60,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 300,
    logCost: 200,
    rockCost: 25,
  },
};
