import { EntityKind } from '@/types';
import type { UnitDef } from './unit-def';

const RESERVED_BUILDING_DEF: UnitDef = {
  hp: 100,
  speed: 0,
  damage: 0,
  attackRange: 0,
  isBuilding: true,
  isResource: false,
  spriteSize: 32,
  spriteScale: 3,
  fishCost: 0,
  logCost: 0,
};

/** Stats and costs for all buildings (player and enemy). */
export const BUILDING_DEFS: Partial<Record<EntityKind, UnitDef>> = {
  [EntityKind.Lodge]: {
    hp: 1500,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 200,
    logCost: 150,
    foodProvided: 8,
  },
  [EntityKind.Burrow]: {
    hp: 300,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 0,
    logCost: 75,
    foodProvided: 6,
    isWing: true,
  },
  [EntityKind.Armory]: {
    hp: 500,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 180,
    logCost: 120,
    isWing: true,
  },
  [EntityKind.Tower]: {
    hp: 500,
    speed: 0,
    damage: 10,
    attackRange: 200,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 200,
    logCost: 250,
  },
  [EntityKind.Watchtower]: {
    hp: 800,
    speed: 0,
    damage: 15,
    attackRange: 280,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 400,
    logCost: 350,
  },
  [EntityKind.PredatorNest]: {
    hp: 1000,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
  },
  [EntityKind.Wall]: {
    hp: 400,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 0,
    logCost: 50,
  },
  [EntityKind.LookoutPost]: {
    hp: 200,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 100,
    logCost: 75,
  },
  [EntityKind.FishingHut]: {
    hp: 250,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 100,
    logCost: 75,
    foodProvided: 2,
    isWing: true,
  },
  [EntityKind.HerbalistHut]: {
    hp: 300,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 150,
    logCost: 100,
    isWing: true,
  },
  // --- v1.5.0 ---
  [EntityKind.Market]: {
    hp: 100,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 150,
    logCost: 100,
    isWing: true,
  },
  [EntityKind.ReservedBuilding39]: RESERVED_BUILDING_DEF,
  [EntityKind.ReservedBuilding42]: RESERVED_BUILDING_DEF,
  [EntityKind.ReservedBuilding43]: RESERVED_BUILDING_DEF,
};
