import { EntityKind } from '@/types';
import type { UnitDef } from './unit-def';

/** Stats and costs for all buildings (player and enemy). */
export const BUILDING_DEFS: Partial<Record<EntityKind, UnitDef>> = {
  [EntityKind.Lodge]: {
    hp: 1500,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 200,
    twigCost: 150,
    foodProvided: 8,
  },
  [EntityKind.Burrow]: {
    hp: 300,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 0,
    twigCost: 75,
    foodProvided: 6,
  },
  [EntityKind.Armory]: {
    hp: 500,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 180,
    twigCost: 120,
  },
  [EntityKind.Tower]: {
    hp: 500,
    speed: 0,
    damage: 10,
    attackRange: 200,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 200,
    twigCost: 250,
  },
  [EntityKind.Watchtower]: {
    hp: 800,
    speed: 0,
    damage: 15,
    attackRange: 280,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 400,
    twigCost: 350,
  },
  [EntityKind.PredatorNest]: {
    hp: 1000,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
  },
  [EntityKind.Wall]: {
    hp: 400,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 0,
    twigCost: 50,
  },
  [EntityKind.ScoutPost]: {
    hp: 200,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 100,
    twigCost: 75,
  },
  [EntityKind.FishingHut]: {
    hp: 250,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 100,
    twigCost: 75,
    foodProvided: 2,
  },
  [EntityKind.HerbalistHut]: {
    hp: 300,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 150,
    twigCost: 100,
  },
  // --- v1.5.0 ---
  [EntityKind.Market]: {
    hp: 100,
    speed: 0,
    damage: 0,
    attackRange: 0,
    isBuilding: true,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    clamCost: 150,
    twigCost: 100,
  },
};
