import { EntityKind } from '@/types';
import type { UnitDef } from './unit-def';

/** Stats for all enemy-spawned units. */
export const ENEMY_UNIT_DEFS: Partial<Record<EntityKind, UnitDef>> = {
  [EntityKind.Gator]: {
    hp: 60,
    speed: 1.8,
    damage: 6,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
  [EntityKind.Snake]: {
    hp: 60,
    speed: 2.0,
    damage: 4,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
  [EntityKind.ArmoredGator]: {
    hp: 120,
    speed: 1.0,
    damage: 8,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
  [EntityKind.VenomSnake]: {
    hp: 40,
    speed: 2.2,
    damage: 3,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
  [EntityKind.SwampDrake]: {
    hp: 50,
    speed: 2.0,
    damage: 6,
    attackRange: 60,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
  [EntityKind.SiegeTurtle]: {
    hp: 300,
    speed: 0.5,
    damage: 25,
    attackRange: 50,
    isBuilding: false,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
  },
  [EntityKind.AlphaPredator]: {
    hp: 500,
    speed: 1.0,
    damage: 12,
    attackRange: 50,
    isBuilding: false,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
  },
  [EntityKind.BossCroc]: {
    hp: 200,
    speed: 1.2,
    damage: 15,
    attackRange: 50,
    isBuilding: false,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
  },
};
