import {
  COMPAT_SABOTEUR_CHASSIS_KIND,
  COMPAT_SAPPER_CHASSIS_KIND,
  LOOKOUT_KIND,
  MEDIC_KIND,
  MUDPAW_KIND,
  SABOTEUR_KIND,
  SAPPER_KIND,
} from '@/game/live-unit-kinds';
import { EntityKind } from '@/types';
import type { UnitDef } from './unit-def';

/**
 * Stats for player-side and compatibility otter units plus ambient neutral critters.
 *
 * Important:
 * - The live player-facing manual roster is `Mudpaw / Medic / Sapper / Saboteur`.
 * - Some older combat chassis ids still exist for compatibility scenarios,
 *   balance tables, and compatibility tests.
 */
export const PLAYER_UNIT_DEFS: Partial<Record<EntityKind, UnitDef>> = {
  // Canonical live manual generalist chassis (`Mudpaw` display label).
  [MUDPAW_KIND]: {
    hp: 30,
    speed: 2.0,
    damage: 2,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 10,
    logCost: 0,
    foodCost: 1,
  },
  // Compatibility otter combat chassis retained for internal coverage.
  [COMPAT_SAPPER_CHASSIS_KIND]: {
    hp: 60,
    speed: 1.8,
    damage: 6,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 20,
    logCost: 0,
    foodCost: 1,
  },
  [COMPAT_SABOTEUR_CHASSIS_KIND]: {
    hp: 40,
    speed: 1.6,
    damage: 8,
    attackRange: 180,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 20,
    logCost: 0,
    foodCost: 1,
  },
  [MEDIC_KIND]: {
    hp: 35,
    speed: 1.8,
    damage: 0,
    attackRange: 0,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 15,
    logCost: 0,
    foodCost: 1,
  },
  [EntityKind.Shieldbearer]: {
    hp: 100,
    speed: 1.4,
    damage: 3,
    attackRange: 35,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 150,
    logCost: 100,
    foodCost: 1,
  },
  // Compatibility recon chassis. The live autonomous recon specialist is
  // `Lookout`, which currently rides this lower-level entity kind.
  [LOOKOUT_KIND]: {
    hp: 20,
    speed: 3.0,
    damage: 1,
    attackRange: 30,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 8,
    logCost: 0,
    foodCost: 1,
  },
  [EntityKind.Catapult]: {
    hp: 50,
    speed: 0.8,
    damage: 20,
    attackRange: 250,
    isBuilding: false,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 300,
    logCost: 200,
    foodCost: 1,
  },
  [EntityKind.Swimmer]: {
    hp: 35,
    speed: 2.8,
    damage: 4,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 60,
    logCost: 30,
    foodCost: 1,
  },
  [EntityKind.Trapper]: {
    hp: 30,
    speed: 1.6,
    damage: 0,
    attackRange: 100,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 80,
    logCost: 60,
    foodCost: 1,
  },
  [EntityKind.Commander]: {
    hp: 150,
    speed: 1.8,
    damage: 8,
    attackRange: 60,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 5.0,
  },
  // --- v1.5.0 new player units ---
  [EntityKind.Diver]: {
    hp: 25,
    speed: 2.5,
    damage: 8,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 60,
    logCost: 40,
    foodCost: 1,
  },
  [EntityKind.Engineer]: {
    hp: 40,
    speed: 1.5,
    damage: 1,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 80,
    logCost: 60,
    foodCost: 1,
  },
  [EntityKind.Shaman]: {
    hp: 30,
    speed: 1.6,
    damage: 0,
    attackRange: 0,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 70,
    logCost: 50,
    foodCost: 1,
  },
  // --- v2.0.0 new player units ---
  [EntityKind.OtterWarship]: {
    hp: 80,
    speed: 1.5,
    damage: 12,
    attackRange: 200,
    isBuilding: false,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 200,
    logCost: 150,
    foodCost: 1,
  },
  [EntityKind.Berserker]: {
    hp: 60,
    speed: 2.0,
    damage: 15,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 120,
    logCost: 80,
    foodCost: 1,
  },
  // --- Canonical live late-stage manual units ---
  [SAPPER_KIND]: {
    hp: 40,
    speed: 1.5,
    damage: 15,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 25,
    rockCost: 15,
    logCost: 0,
    foodCost: 1,
  },
  [SABOTEUR_KIND]: {
    hp: 30,
    speed: 2.5,
    damage: 5,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 20,
    rockCost: 10,
    logCost: 0,
    foodCost: 1,
  },
  // Ambient critters (no cost, no combat role)
  [EntityKind.Frog]: {
    hp: 5,
    speed: 0.5,
    damage: 0,
    attackRange: 0,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
  [EntityKind.Fish]: {
    hp: 5,
    speed: 1.0,
    damage: 0,
    attackRange: 0,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
};
