import { EntityKind } from '@/types';
import type { UnitDef } from './unit-def';

/** Stats for all player-trainable units plus ambient neutral critters. */
// v3 costs aligned with configs/units.json (Fish-only for basic generalists)
export const PLAYER_UNIT_DEFS: Partial<Record<EntityKind, UnitDef>> = {
  [EntityKind.Gatherer]: {
    hp: 30,
    speed: 2.0,
    damage: 2,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 10,
    logCost: 0,
    foodCost: 1,
  },
  [EntityKind.Brawler]: {
    hp: 60,
    speed: 1.8,
    damage: 6,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 20,
    logCost: 0,
    foodCost: 1,
  },
  [EntityKind.Sniper]: {
    hp: 40,
    speed: 1.6,
    damage: 8,
    attackRange: 180,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 20,
    logCost: 0,
    foodCost: 1,
  },
  [EntityKind.Healer]: {
    hp: 35,
    speed: 1.8,
    damage: 0,
    attackRange: 0,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 15,
    logCost: 0,
    foodCost: 1,
  },
  [EntityKind.Shieldbearer]: {
    hp: 100,
    speed: 1.4,
    damage: 3,
    attackRange: 35,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 150,
    logCost: 100,
    foodCost: 1,
  },
  [EntityKind.Scout]: {
    hp: 20,
    speed: 3.0,
    damage: 1,
    attackRange: 30,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 8,
    logCost: 0,
    foodCost: 1,
  },
  [EntityKind.Catapult]: {
    hp: 50,
    speed: 0.8,
    damage: 20,
    attackRange: 250,
    isBuilding: false,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 300,
    logCost: 200,
    foodCost: 1,
  },
  [EntityKind.Swimmer]: {
    hp: 35,
    speed: 2.8,
    damage: 4,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 60,
    logCost: 30,
    foodCost: 1,
  },
  [EntityKind.Trapper]: {
    hp: 30,
    speed: 1.6,
    damage: 0,
    attackRange: 100,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 80,
    logCost: 60,
    foodCost: 1,
  },
  [EntityKind.Commander]: {
    hp: 150,
    speed: 1.8,
    damage: 8,
    attackRange: 60,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 5.0,
  },
  // --- v1.5.0 new player units ---
  [EntityKind.Diver]: {
    hp: 25,
    speed: 2.5,
    damage: 8,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 60,
    logCost: 40,
    foodCost: 1,
  },
  [EntityKind.Engineer]: {
    hp: 40,
    speed: 1.5,
    damage: 1,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 80,
    logCost: 60,
    foodCost: 1,
  },
  [EntityKind.Shaman]: {
    hp: 30,
    speed: 1.6,
    damage: 0,
    attackRange: 0,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 70,
    logCost: 50,
    foodCost: 1,
  },
  // --- v2.0.0 new player units ---
  [EntityKind.OtterWarship]: {
    hp: 80,
    speed: 1.5,
    damage: 12,
    attackRange: 200,
    isBuilding: false,
    isResource: false,
    spriteSize: 32,
    spriteScale: 3,
    fishCost: 200,
    logCost: 150,
    foodCost: 1,
  },
  [EntityKind.Berserker]: {
    hp: 60,
    speed: 2.0,
    damage: 15,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 120,
    logCost: 80,
    foodCost: 1,
  },
  // --- v3.0.0 new player units ---
  [EntityKind.Sapper]: {
    hp: 40,
    speed: 1.5,
    damage: 15,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 25,
    rockCost: 15,
    logCost: 0,
    foodCost: 1,
  },
  [EntityKind.Saboteur]: {
    hp: 30,
    speed: 2.5,
    damage: 5,
    attackRange: 40,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
    fishCost: 20,
    rockCost: 10,
    logCost: 0,
    foodCost: 1,
  },
  // Ambient critters (no cost, no combat role)
  [EntityKind.Frog]: {
    hp: 5,
    speed: 0.5,
    damage: 0,
    attackRange: 0,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
  [EntityKind.Fish]: {
    hp: 5,
    speed: 1.0,
    damage: 0,
    attackRange: 0,
    isBuilding: false,
    isResource: false,
    spriteSize: 16,
    spriteScale: 2.5,
  },
};
