export {
  closeDatabase,
  deleteSave,
  getLatestSave,
  getPlayerProfile,
  getSetting,
  getUnlock,
  initDatabase,
  isDatabaseReady,
  listSaves,
  listUnlocks,
  loadSave,
  type PlayerProfile,
  persist,
  recordGameResult,
  type SaveRow,
  saveGameToDb,
  setSetting,
  setUnlock,
  updatePlayerProfile,
  updateSave,
} from './database';
export {
  getMatchHistory,
  type MatchRecord,
  saveMatchRecord,
} from './match-history';
