export {
  closeDatabase,
  deleteSave,
  getLatestSave,
  getSetting,
  initDatabase,
  isDatabaseReady,
  listSaves,
  loadSave,
  persist,
  recordGameResult,
  type SaveRow,
  saveGameToDb,
  setSetting,
  updateSave,
} from './database';
