export {
  closeDatabase,
  deleteSave,
  getLatestSave,
  getSetting,
  getPlayerProfile,
  getUnlock,
  initDatabase,
  isDatabaseReady,
  listSaves,
  listUnlocks,
  loadSave,
  persist,
  type PlayerProfile,
  recordGameResult,
  type SaveRow,
  saveGameToDb,
  setSetting,
  setUnlock,
  updatePlayerProfile,
  updateSave,
} from './database';
